### ISSUE TITLE
`showvalue` not defined in `Logging` in Julia 1.11

### ISSUE THREAD

**Issue by hexaeder** [julia-actions/GitHubActions.jl#36]
Sometimes in my doc builds, it get the following error

```julia
ERROR: LoadError: UndefVarError: `showvalue` not defined in `Logging`
```

And indeed `Logging.showvalue` is called in this function

https://github.com/julia-actions/GitHubActions.jl/blob/e988cc204e34bf1b12b28c3f1f00e5ae347af30f/src/GitHubActions.jl#L259C1-L259C46

but does not appear to be defined in Julia 1.11

**Comment by moyner** [comment]
Same here: https://github.com/sintefmath/JutulDarcy.jl/actions/runs/11243998227/job/31274362490?pr=68

**Comment by rafaqz** [comment]
Same problem
https://github.com/rafaqz/DimensionalData.jl/actions/runs/11269812123/job/31339182058?pr=818#step:6:97

**Comment by Pangoraw** [comment]
See #37
