### ISSUE TITLE
Commands set-env and add-path are being deprecated

### ISSUE THREAD

**Issue by SaschaMann** [julia-actions/GitHubActions.jl#4]
I received Dependabot alerts on the `toolkit/core` js package that the way to set environment variables and to add dirs to the path is changing. I assume the Julia implementation of it also needs to be changed. I'm not sure of the deprecation timeline.

Changes: https://github.com/actions/toolkit/pull/571/files
Info on how it works: https://github.com/actions/toolkit/blob/main/docs/commands.md#environment-files

**Comment by christopher-dG** [comment]
#6
