### ISSUE TITLE
Specify file & line for logging commands

### ISSUE THREAD

**Issue by SaschaMann** [julia-actions/GitHubActions.jl#5]
Would there be a way to specify which file and line the logging notification is meant to be attached to?

I have a CI script where I use `@warn` if something is wrong with a file. Right now, it attaches all warnings to the line of `@warn` but I'd like to pass a file name and line number to `@warn` so that it attaches the warning to the file that caused the warning.

Example:
![grafik](https://user-images.githubusercontent.com/20866761/97784837-91848d80-1ba1-11eb-92ee-27a30bc83074.png)

(scroll down; for some reason I can't actually link the build and have it show those annotations)

Not sure I described what I want clearly :D

**Comment by christopher-dG** [comment]
I think we can make this work somehow.

Currently we just use the info given to us in the log handler but I think you can pass custom arguments too. I'll have a look.

https://github.com/julia-actions/GitHubActions.jl/blob/302740d513e58ab753d10d123f7fc8db41c839f8/src/GitHubActions.jl#L219-L238
